AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
  DisplayCopNames: true

# Styles

Style/AndOr:
  EnforcedStyle: conditionals

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExtraSpacing:
  Exclude:
    - 'db/migrate/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/Lambda:
  EnforcedStyle: literal

Style/NumericLiterals:
  MinDigits: 7

# Metrics

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*.rb'
